### ISSUE TITLE
量化部署无效

### ISSUE THREAD

**Issue by bxjxxyy** [baichuan-inc/Baichuan-13B#85]
显卡配置：4090 24G显存
![image](https://github.com/baichuan-inc/Baichuan-13B/assets/26214176/54051b61-6cfd-4d1a-a21f-a65d60a93efa)
代码添加了int8量化，启动的时候还是报错现存不足
OutOfMemoryError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 0; 23.65 GiB total capacity; 22.36 GiB already allocated; 188.56 MiB free; 22.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by lfxx** [comment]
> 显卡配置：4090 24G显存 ![image](https://user-images.githubusercontent.com/26214176/254497039-54051b61-6cfd-4d1a-a21f-a65d60a93efa.png) 代码添加了int8量化，启动的时候还是报错现存不足 OutOfMemoryError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 0; 23.65 GiB total capacity; 22.36 GiB already allocated; 188.56 MiB free; 22.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

你需要把device_map="auto"去除，然后重新量化

**Comment by dawn2034** [comment]
@lfxx 请问量化后的模型如何保存呢？

**Comment by bxjxxyy** [comment]
> > 显卡配置：4090 24G显存 ![image](https://user-images.githubusercontent.com/26214176/254497039-54051b61-6cfd-4d1a-a21f-a65d60a93efa.png) 代码添加了int8量化，启动的时候还是报错现存不足 OutOfMemoryError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 0; 23.65 GiB total capacity; 22.36 GiB already allocated; 188.56 MiB free; 22.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 你需要把device_map="auto"去除，然后重新量化

  多谢 解决了。没仔细看给的代码里面就是去掉了这个
